name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GITHUB_SHA: ${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag dr460neye/doctoolchain:"$GITHUB_SHA" .
    - name: Check image
      run: docker image ls -a
    - name: Publish
      run: |
        docker push dr460neye/doctoolchain:$GITHUB_SHA
